const fs=require("fs");
const p="site/public/index.html";
let s=fs.readFileSync(p,"utf8");
const css=`
.admin-corner{position:absolute;left:12px;top:12px;z-index:8;display:none;gap:8px;flex-wrap:wrap}.admin-corner.on{display:flex}.admin-corner button{border:0;border-radius:12px;background:rgba(255,253,249,.97);color:#284b40;font-weight:850;padding:10px 12px;box-shadow:0 2px 8px rgba(0,0,0,.12);font-size:14px}.clients-btn{position:relative}.clients-badge{display:none;position:absolute;right:-7px;top:-7px;min-width:23px;height:23px;padding:0 6px;border-radius:99px;background:#bd493c;color:#fff;border:2px solid #fff;place-items:center;font-size:12px}.clients-badge.on{display:grid}.admin-sheet{position:fixed;inset:0;z-index:110;background:rgba(16,20,18,.58);display:none;align-items:flex-end;justify-content:center}.admin-sheet.on{display:flex}.admin-panel{width:min(100%,680px);max-height:92vh;overflow:auto;background:#f8f4ed;border-radius:24px 24px 0 0;padding:18px 16px 28px}.admin-panel h2{margin:2px 0 14px;color:#284b40}.panel-close{float:right;border:0;background:#fff;border-radius:10px;padding:9px 12px;font-weight:800}.admin-settings-grid{display:grid;gap:10px}.admin-settings-grid input{padding:13px 14px;border:1px solid #d9d1c4;border-radius:12px;font-size:17px}.admin-main-btn{border:0;border-radius:13px;padding:13px 15px;background:#405f50;color:#fff;font-size:16px;font-weight:900}.admin-note{font-size:13px;color:#6b6e69}.order-admin-list{display:grid;gap:12px}.admin-order{background:#fff;border:1px solid #ddd5ca;border-radius:16px;padding:13px}.admin-order.done{opacity:.72}.admin-order-top{display:flex;justify-content:space-between;gap:10px}.admin-order-name{font-size:19px;font-weight:900;color:#284b40}.admin-order-date{font-size:12px;color:#767771;text-align:right}.admin-order-items{margin:10px 0;font-size:14px;line-height:1.45}.admin-order-total{font-size:18px;font-weight:900}.admin-order-actions{display:grid;grid-template-columns:1fr auto;gap:8px}.order-state-btn,.order-pdf-btn{border:0;border-radius:12px;padding:12px 10px;font-size:15px;font-weight:900}.order-state-btn{background:#405f50;color:#fff}.order-state-btn[disabled]{background:#e6e0d7;color:#666}.order-pdf-btn{border:1px solid #cfc6b8;background:#fff;color:#405f50}.admin-alert{position:fixed;inset:0;z-index:160;background:rgba(24,53,44,.97);color:#fff;display:none;align-items:center;justify-content:center;padding:24px;text-align:center}.admin-alert.on{display:flex}.admin-alert-card{width:min(100%,560px)}.admin-alert-card h2{font-size:33px;margin:0 0 12px;font-family:Georgia,serif}.admin-alert-card .who{font-size:22px;font-weight:900}.admin-alert-card .summary{font-size:17px;line-height:1.5;white-space:pre-line}.admin-alert-card .tap{font-size:13px;opacity:.72;margin-top:30px}@media(max-width:620px){.admin-corner{left:8px;top:8px}.admin-corner button{font-size:13px;padding:9px 10px}.admin-order-actions{grid-template-columns:1fr}}`;
s=s.replace("</style>",css+"</style>");
s=s.replace('<div class="top-actions">','<div class="admin-corner" id="adminCorner"><button id="adminSettingsBtn">⚙️ Réglages</button><button class="clients-btn" id="adminClientsBtn">Clients<span class="clients-badge" id="clientsBadge">0</span></button></div><div class="top-actions">');
const ui=`
<div class="admin-sheet" id="adminSettingsSheet"><div class="admin-panel"><button class="panel-close" id="closeAdminSettings">Fermer</button><h2>Réglages — <span id="settingsAdminName">Administrateur</span></h2><div class="admin-settings-grid"><input id="currentAdminCode" type="password" placeholder="Code actuel"><input id="newAdminCode" type="password" placeholder="Nouveau code — lettres et/ou chiffres"><input id="confirmAdminCode" type="password" placeholder="Confirmer le nouveau code"><button class="admin-main-btn" id="changeAdminCodeBtn">Changer mon code</button><div class="admin-note" id="adminSettingsMessage"></div></div></div></div>
<div class="admin-sheet" id="adminClientsSheet"><div class="admin-panel"><button class="panel-close" id="closeAdminClients">Fermer</button><h2>Clients et commandes</h2><div class="order-admin-list" id="adminOrderList"></div></div></div>
<div class="admin-alert" id="adminFullAlert"><div class="admin-alert-card"><h2 id="adminAlertTitle">Nouvelle commande</h2><div class="who" id="adminAlertWho"></div><div class="summary" id="adminAlertSummary"></div><div class="tap">Touchez l’écran pour fermer</div></div></div>
`;
s=s.replace('<div class="update-loader" id="updateLoader">',ui+'<div class="update-loader" id="updateLoader">');
const js=`
const adminTokenKey="marlene-et-moi-admin-token-v1",adminRevisionKey="marlene-et-moi-admin-revision-v1";
let adminToken=safeGet(adminTokenKey)||"",adminOrders=[],adminRevision=parseInt(safeGet(adminRevisionKey)||"0",10)||0,adminPollTimer=null;
async function apiJson(path,options={}){const headers=Object.assign({"Content-Type":"application/json"},options.headers||{});if(adminToken)headers.Authorization="Bearer "+adminToken;const r=await fetch(path,Object.assign({},options,{headers,cache:"no-store"}));let d={};try{d=await r.json()}catch(e){}if(!r.ok)throw new Error(d.error||("Erreur "+r.status));return d}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function showAdminFullAlert(t,w,m){if(!admin)return;adminAlertTitle.textContent=t||"Commande";adminAlertWho.textContent=w||"";adminAlertSummary.textContent=m||"";adminFullAlert.classList.add("on")}
adminFullAlert.onclick=()=>adminFullAlert.classList.remove("on");
async function refreshServerStatus(){try{const d=await apiJson("/api/status",{method:"GET"});if(d.adminsReady){adminsReady=true;if(lockBtn)lockBtn.classList.add("hidden")}}catch(e){}}
function updateAdminChrome(){adminCorner.classList.toggle("on",admin);settingsAdminName.textContent=adminWho||"Administrateur";const n=adminOrders.filter(o=>o.status!=="done").length;clientsBadge.textContent=n;clientsBadge.classList.toggle("on",n>0)}
function orderSummary(o){return(o.items||[]).map(x=>x.name+" ×"+x.qty).join(" · ")+"\nTotal : "+(o.totalText||"")}
function renderAdminOrders(){if(!adminOrders.length){adminOrderList.innerHTML='<div class="admin-order">Aucune commande.</div>';return}adminOrderList.innerHTML="";adminOrders.forEach(o=>{const c=document.createElement("div");c.className="admin-order"+(o.status==="done"?" done":"");let label="Je m'en occupe",action="claim",disabled=false;if(o.status==="in_progress"){if(o.assignedTo===adminWho){label="Commande terminée";action="finish"}else{label=(o.assignedTo||"Quelqu’un")+" s’en occupe";disabled=true}}else if(o.status==="done"){label="Terminée par "+(o.completedBy||o.assignedTo||"administrateur");disabled=true}c.innerHTML='<div class="admin-order-top"><div><div class="admin-order-name">'+esc(o.first)+" "+esc(o.last)+'</div><div>'+esc(o.phone||"")+" · "+esc(o.email||"")+'</div></div><div class="admin-order-date">'+new Date(o.createdAt).toLocaleString("fr-FR")+'</div></div><div class="admin-order-items">'+(o.items||[]).map(x=>esc(x.name)+" ×"+x.qty+" — "+esc(x.lineTotal||"")).join("<br>")+"<br><b>"+esc(o.deliveryText||"")+'</b></div><div class="admin-order-total">'+esc(o.totalText||"")+'</div><div class="admin-order-actions"><button class="order-state-btn" '+(disabled?"disabled":"")+">"+esc(label)+'</button><button class="order-pdf-btn">PDF</button></div>';const b=c.querySelector(".order-state-btn");if(!disabled&&action==="claim")b.onclick=()=>claimOrder(o.id);if(!disabled&&action==="finish")b.onclick=()=>finishOrder(o.id);c.querySelector(".order-pdf-btn").onclick=()=>downloadOrderPdf(o);adminOrderList.appendChild(c)})}
function downloadOrderPdf(o){const txt=["MARLENE ET MOI","COMMANDE CLIENT","","Client : "+o.first+" "+o.last,"E-mail : "+(o.email||""),"Telephone : "+(o.phone||""),"Mode : "+(o.deliveryText||""),"",...(o.items||[]).map(x=>x.name+" x"+x.qty+"  "+(x.lineTotal||"")),"","TOTAL : "+(o.totalText||"")].join("\n");const blob=new Blob([txt],{type:"application/pdf"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="commande-"+o.id+".pdf";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function loadAdminOrders(events=true){if(!admin||!adminToken)return;try{const d=await apiJson("/api/admin/orders",{method:"GET"});adminOrders=d.orders||[];const r=Number(d.revision||0);if(events&&r>adminRevision&&d.lastEvent){const e=d.lastEvent;if(e.type==="new_order")showAdminFullAlert("Nouvelle commande",e.orderName||"",e.summary||"");else if(e.by&&e.by!==adminWho&&e.type==="claimed")showAdminFullAlert(e.by+" s’en occupe","Commande prise en charge",e.summary||"");else if(e.by&&e.by!==adminWho&&e.type==="done")showAdminFullAlert("Commande terminée par "+e.by,"Aucune action nécessaire",e.summary||"")}if(r>adminRevision){adminRevision=r;safeSet(adminRevisionKey,String(r))}renderAdminOrders();updateAdminChrome()}catch(e){}}
function startAdminPolling(){if(adminPollTimer)clearInterval(adminPollTimer);if(!admin||!adminToken)return;loadAdminOrders(false);adminPollTimer=setInterval(()=>loadAdminOrders(true),3000)}
async function claimOrder(id){try{await apiJson("/api/admin/order/claim",{method:"POST",body:JSON.stringify({id})});await loadAdminOrders(false)}catch(e){showAdminFullAlert("Commande déjà prise","",e.message)}}
async function finishOrder(id){try{await apiJson("/api/admin/order/finish",{method:"POST",body:JSON.stringify({id})});await loadAdminOrders(false)}catch(e){showAdminFullAlert("Impossible","",e.message)}}
adminSettingsBtn.onclick=()=>{currentAdminCode.value="";newAdminCode.value="";confirmAdminCode.value="";adminSettingsMessage.textContent="";adminSettingsSheet.classList.add("on")};closeAdminSettings.onclick=()=>adminSettingsSheet.classList.remove("on");
adminClientsBtn.onclick=()=>{adminClientsSheet.classList.add("on");renderAdminOrders();loadAdminOrders(false)};closeAdminClients.onclick=()=>adminClientsSheet.classList.remove("on");
changeAdminCodeBtn.onclick=async()=>{const c=currentAdminCode.value,n=newAdminCode.value,k=confirmAdminCode.value;if(!c||!n){adminSettingsMessage.textContent="Remplis les 3 cases.";return}if(n!==k){adminSettingsMessage.textContent="Les deux nouveaux codes ne sont pas identiques.";return}if(n.length<4){adminSettingsMessage.textContent="Mets au moins 4 caractères.";return}try{await apiJson("/api/admin/change-code",{method:"POST",body:JSON.stringify({currentCode:c,newCode:n})});adminSettingsMessage.textContent="Code changé."}catch(e){adminSettingsMessage.textContent=e.message}};
async function createServerOrder(first,last,email,phone){const rows=cartItems();return apiJson("/api/order",{method:"POST",body:JSON.stringify({first,last,email,phone,deliveryText:deliveryMode==="pickup"?"À venir chercher — "+selectedMarket:"Envoyer",totalText:formatEuro(cartTotalValue()),items:rows.map(({p,qty})=>({name:p.name,qty,lineTotal:formatEuro(euroValue(p.price)*qty),price:p.price}))})})}
`;
s=s.replace("function quoteHtml(first,last,email,phone){",js+"function quoteHtml(first,last,email,phone){");
s=s.replace(/document\.getElementById\('sendOrder'\)\.onclick=async\(\)=>\{[\s\S]*?\n\};\n\nfunction openAdminBox/, `document.getElementById('sendOrder').onclick=async()=>{const first=buyerFirst.value.trim(),last=buyerLast.value.trim(),email=buyerEmail.value.trim(),phone=buyerPhone.value.trim();if(!first||!last||!email||!email.includes("@")||!phone)return;try{await createServerOrder(first,last,email,phone);orderForm.classList.remove("on");cart=[];saveCart();renderCart();render();showToast("Commande envoyée")}catch(e){const subject="Commande Marlene et moi — "+first+" "+last,body=textOrder(first,last,email,phone);try{location.href="mailto:"+sellerEmail+"?subject="+encodeURIComponent(subject)+"&body="+encodeURIComponent(body)}catch(_e){}}};\n\nfunction openAdminBox`);
s=s.replace(/document\.getElementById\('okLogin'\)\.onclick=\(\)=>\{[\s\S]*?\n\};\n\nlet pressTimer=null;/,`document.getElementById('okLogin').onclick=async()=>{const box=loginBox;if(box.dataset.mode==="setup"){const a1=admin1Input.value.trim(),a2=admin2Input.value.trim();if(!a1||!a2||a1===a2)return;try{const d=await apiJson("/api/admin/setup",{method:"POST",body:JSON.stringify({johnCode:a1,marleneCode:a2})});adminsReady=true;admin=true;adminWho="John";selectedAdminWho="John";adminToken=d.token||"";safeSet(adminTokenKey,adminToken);safeSet(adminWhoKey,adminWho);safeSet(adminSessionKey,"1");box.classList.remove("on");render();startAdminPolling()}catch(e){adminsReady=true;openAdminBox("login")}return}const code=codeInput.value.trim();try{const d=await apiJson("/api/admin/login",{method:"POST",body:JSON.stringify({admin:selectedAdminWho,code})});admin=true;adminWho=selectedAdminWho;adminToken=d.token||"";safeSet(adminTokenKey,adminToken);safeSet(adminWhoKey,adminWho);safeSet(adminSessionKey,"1");box.classList.remove("on");render();startAdminPolling()}catch(e){}};\n\nlet pressTimer=null;`);
s=s.replace("if(adminToolbar) adminToolbar.classList.toggle('on', admin);","if(adminToolbar) adminToolbar.classList.toggle('on', admin); updateAdminChrome();");
s=s.replace("renderCart();\n\ntry{","refreshServerStatus().then(()=>{if(admin&&adminToken)startAdminPolling();render()});\nrenderCart();\n\ntry{");
fs.writeFileSync(p,s);
let sw="site/public/sw.js";let w=fs.readFileSync(sw,"utf8").replace(/const CACHE='marlene-et-moi-v\\d+';/,"const CACHE='marlene-et-moi-v20';");fs.writeFileSync(sw,w);
