(()=>{
if(window.__M21_EFFECTS__)return;window.__M21_EFFECTS__=1;
const css=document.createElement('style');
css.textContent='.cart-yarn-flight-v21{position:fixed;inset:0;z-index:99997;pointer-events:none;overflow:visible}.cart-yarn-flight-v21 path.shadow{fill:none;stroke:rgba(35,55,48,.18);stroke-width:16;stroke-linecap:round}.cart-yarn-flight-v21 path.main{fill:none;stroke:url(#m21g);stroke-width:10;stroke-linecap:round;filter:drop-shadow(0 2px 2px rgba(0,0,0,.16))}.cart-yarn-photo-v21{position:fixed;z-index:99999;width:68px;height:68px;border-radius:18px;object-fit:cover;border:4px solid #fff;box-shadow:0 14px 30px rgba(0,0,0,.30);pointer-events:none;transform:translate(-50%,-50%)}.cart-pop-v21{animation:cartPopV21 .65s ease}@keyframes cartPopV21{0%{transform:scale(1)}35%{transform:scale(1.23) rotate(-5deg)}65%{transform:scale(.96) rotate(3deg)}100%{transform:scale(1)}}.continuous-yarn-v21{position:absolute;left:82px;top:20px;width:270px;height:86px;overflow:visible;pointer-events:none}.continuous-yarn-v21 .lead{fill:none;stroke:url(#m21loaderg);stroke-width:7;stroke-linecap:round;stroke-dasharray:92;stroke-dashoffset:92;animation:m21Lead 6.6s ease-in-out infinite}.continuous-yarn-v21 .word{font-family:Georgia,serif;font-style:italic;font-weight:700;font-size:58px;fill:none;stroke:url(#m21loaderg);stroke-width:5.2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:760;stroke-dashoffset:760;animation:m21Word 6.6s ease-in-out infinite}.loader-ball{animation:m21Ball 6.6s ease-in-out infinite!important}@keyframes m21Lead{0%,7%{stroke-dashoffset:92}18%{stroke-dashoffset:0}62%{stroke-dashoffset:0}92%,100%{stroke-dashoffset:92}}@keyframes m21Word{0%,13%{stroke-dashoffset:760;opacity:0}19%{opacity:1}52%,62%{stroke-dashoffset:0;opacity:1}76%{stroke-dashoffset:260}90%{stroke-dashoffset:650}100%{stroke-dashoffset:760;opacity:0}}@keyframes m21Ball{0%{transform:translateY(0) rotate(0)}10%{transform:translateY(-8px) rotate(-7deg)}18%{transform:translateY(0) rotate(6deg)}30%{transform:translateY(-10px) rotate(13deg)}42%{transform:translateY(0) rotate(17deg)}56%{transform:translateY(-6px) rotate(12deg)}70%{transform:translateY(0) rotate(5deg)}84%{transform:translateY(-5px) rotate(-2deg)}100%{transform:translateY(0) rotate(-10deg)}}@media(max-width:620px){.continuous-yarn-v21{left:75px;top:25px;width:215px;height:70px}.continuous-yarn-v21 .word{font-size:46px;stroke-width:4.6}.continuous-yarn-v21 .lead{stroke-width:6}}';
document.head.appendChild(css);

function installLoader(){
 const a=document.querySelector('.update-anim'); if(!a||a.querySelector('.continuous-yarn-v21'))return;
 const oldT=a.querySelector('.loader-thread'),oldW=a.querySelector('.loader-wordmark'); if(oldT)oldT.style.display='none'; if(oldW)oldW.style.display='none';
 const ns='http://www.w3.org/2000/svg',s=document.createElementNS(ns,'svg');s.setAttribute('class','continuous-yarn-v21');s.setAttribute('viewBox','0 0 560 130');s.setAttribute('aria-hidden','true');
 s.innerHTML='<defs><linearGradient id="m21loaderg" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" stop-color="#d7b6a6"/><stop offset="22%" stop-color="#d8c5a3"/><stop offset="48%" stop-color="#a8bfd8"/><stop offset="72%" stop-color="#d7afb3"/><stop offset="100%" stop-color="#b4b0ad"/></linearGradient></defs><path class="lead" d="M 0 72 C 24 72, 45 66, 73 67 S 91 70, 100 72"/><text class="word" x="92" y="88">Marlène et moi</text>';
 a.appendChild(s);
}

function animateToCart(btn){
 const target=document.getElementById('cartBtn'); const card=btn.closest('.card'); const img=card&&card.querySelector('.photo img'); if(!target||!img)return;
 const a=btn.getBoundingClientRect(),b=target.getBoundingClientRect(); const sx=a.left+a.width/2,sy=a.top+a.height/2,ex=b.left+b.width/2,ey=b.top+b.height/2;
 const bend=Math.max(95,Math.abs(ex-sx)*.34),c1x=sx+(ex>sx?bend:-bend),c1y=sy-85,c2x=ex+(ex>sx?-bend*.7:bend*.7),c2y=ey+65,d='M '+sx+' '+sy+' C '+c1x+' '+c1y+', '+c2x+' '+c2y+', '+ex+' '+ey;
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('class','cart-yarn-flight-v21');svg.setAttribute('width',innerWidth);svg.setAttribute('height',innerHeight);svg.setAttribute('viewBox','0 0 '+innerWidth+' '+innerHeight);
 svg.innerHTML='<defs><linearGradient id="m21g" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" stop-color="#d7b6a6"/><stop offset="22%" stop-color="#d8c5a3"/><stop offset="48%" stop-color="#a8bfd8"/><stop offset="72%" stop-color="#d7afb3"/><stop offset="100%" stop-color="#b4b0ad"/></linearGradient></defs><path class="shadow" d="'+d+'"/><path class="main" d="'+d+'"/>';document.body.appendChild(svg);
 const main=svg.querySelector('.main'),shadow=svg.querySelector('.shadow'),len=main.getTotalLength();[main,shadow].forEach(p=>{p.style.strokeDasharray=len;p.style.strokeDashoffset=len});
 const fly=document.createElement('img');fly.className='cart-yarn-photo-v21';fly.src=img.currentSrc||img.src;fly.style.left=sx+'px';fly.style.top=sy+'px';document.body.appendChild(fly);
 const dur=1650,start=performance.now();function f(now){const t=Math.min(1,(now-start)/dur),e=1-Math.pow(1-t,3),off=len*(1-e);main.style.strokeDashoffset=off;shadow.style.strokeDashoffset=off;const p=main.getPointAtLength(len*e);fly.style.left=p.x+'px';fly.style.top=p.y+'px';fly.style.transform='translate(-50%,-50%) rotate('+(e*20-6)+'deg) scale('+(1-e*.5)+')';if(t<1)requestAnimationFrame(f);else{target.classList.remove('cart-pop-v21');void target.offsetWidth;target.classList.add('cart-pop-v21');setTimeout(()=>{svg.style.transition='opacity .4s';svg.style.opacity='0';fly.style.transition='opacity .3s,transform .3s';fly.style.opacity='0';fly.style.transform='translate(-50%,-50%) scale(.12)'},180);setTimeout(()=>{svg.remove();fly.remove();target.classList.remove('cart-pop-v21')},750)}}requestAnimationFrame(f);
}
document.addEventListener('click',e=>{const b=e.target.closest('.add-cart-btn,.mini-cart-btn,.cart-add-btn');if(b)animateToCart(b)},true);
installLoader();new MutationObserver(installLoader).observe(document.documentElement,{childList:true,subtree:true});
})();