(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const CART='me-cart-v100',TOKEN='me-admin-token-v100',ADMIN='me-admin-name-v100',TRACK='me-track-v100',KNOWN='me-known-v100';
const sg=k=>{try{return localStorage.getItem(k)}catch{return null}},ss=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('on');clearTimeout(toast._t);t._t=setTimeout(()=>t.classList.remove('on'),1800)};
const money=n=>(Number(n)||0).toLocaleString('fr-FR',{minimumFractionDigits:0,maximumFractionDigits:2})+' €';
const euro=v=>Number(String(v).replace(/[^0-9,.-]/g,'').replace(',','.'))||0;
const show=id=>{$('#'+id).classList.add('on')},hide=id=>{$('#'+id).classList.remove('on')};
let token=sg(TOKEN)||'',adminName=sg(ADMIN)||'',isAdmin=!!token,selectedAdmin='John',current='echarpes',color='toutes',page=1,delivery='ship',market='',gift=false,editing=null,viewer=null,viewerIndex=0,tab='active';
let cart=[];try{cart=JSON.parse(sg(CART)||'[]')}catch{}
let products={echarpes:[],vestes:[],bracelets:[]};
const labels={echarpes:'Écharpes',vestes:'Vestes',bracelets:'Bracelets'};
const COLORS=[
{id:'toutes',label:'Toutes',hex:'linear-gradient(135deg,#2e8b57,#e34b4b,#3b82f6,#f1c84b,#111)'},
{id:'vert',label:'Vert',hex:'#3f7f59',shades:['Vert','Vert clair','Vert foncé','Vert pomme','Vert olive','Vert sapin','Vert menthe','Kaki']},
{id:'bleu',label:'Bleu',hex:'#3d6fa8',shades:['Bleu','Bleu clair','Bleu foncé','Bleu marine','Bleu ciel','Bleu glacier','Bleu roi','Turquoise']},
{id:'rouge',label:'Rouge',hex:'#b54b4b',shades:['Rouge','Rouge clair','Rouge foncé','Bordeaux','Grenat','Framboise']},
{id:'rose',label:'Rose',hex:'#d78fa4',shades:['Rose','Rose clair','Rose poudré','Vieux rose','Fuchsia','Saumon']},
{id:'violet',label:'Violet',hex:'#80569c',shades:['Violet','Violet clair','Violet foncé','Prune','Lilas','Lavande']},
{id:'jaune',label:'Jaune',hex:'#e2bd3c',shades:['Jaune','Jaune clair','Moutarde','Or','Citron']},
{id:'orange',label:'Orange',hex:'#d77d35',shades:['Orange','Orange clair','Orange foncé','Terracotta','Cuivre']},
{id:'beige',label:'Beige',hex:'#d2bea0',shades:['Beige','Écru','Crème','Sable','Camel','Taupe']},
{id:'marron',label:'Marron',hex:'#76513c',shades:['Marron','Marron clair','Marron foncé','Chocolat','Noisette','Caramel']},
{id:'gris',label:'Gris',hex:'#8e9294',shades:['Gris','Gris clair','Gris foncé','Anthracite','Argent']},
{id:'noir',label:'Noir',hex:'#202020',shades:['Noir','Noir profond']},
{id:'blanc',label:'Blanc',hex:'#f5f3ec',shades:['Blanc','Blanc cassé','Ivoire']},
{id:'multicolore',label:'Multicolore',hex:'linear-gradient(135deg,#e76f51,#f4d35e,#2a9d8f,#457b9d,#9b5de5)',shades:['Multicolore']}
];
const fam=id=>COLORS.find(x=>x.id===id)||COLORS[COLORS.length-1];
async function api(path,opt={}){const h={'content-type':'application/json',...(opt.headers||{})};if(token)h.authorization='Bearer '+token;const r=await fetch(path,{...opt,headers:h,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Erreur');return d}
function loader(on){$('#loader').classList.toggle('on',on)}
async function refreshCatalog(showNew=false){try{const d=await api('/api/catalog');products=d.products||products;render();if(showNew){let known=[];try{known=JSON.parse(sg(KNOWN)||'[]')}catch{}const all=Object.entries(products).flatMap(([cat,list])=>list.map(p=>({...p,cat})));const fresh=all.find(p=>!known.includes(p.id));ss(KNOWN,JSON.stringify(all.map(p=>p.id)));if(fresh){$('#newItemImg').src=fresh.imgs?.[0]||'';$('#newItemName').textContent=fresh.name;$('#newItemInfo').textContent=fresh.info||'';$('#newItemSee').onclick=()=>{hide('newItemModal');current=fresh.cat;color='toutes';page=Math.floor((products[current].findIndex(x=>x.id===fresh.id))/10)+1;render();setTimeout(()=>document.querySelector('[data-id="'+fresh.id+'"]')?.scrollIntoView({behavior:'smooth',block:'center'}),100)};show('newItemModal')}}}catch(e){toast('Connexion impossible')}}
function renderColors(){const box=$('#colorFilters');box.innerHTML='';COLORS.forEach(c=>{const b=document.createElement('button');b.className='color-chip'+(color===c.id?' active':'');b.innerHTML='<span class="dot" style="background:'+c.hex+'"></span>'+c.label;b.onclick=()=>{color=c.id;page=1;render()};box.appendChild(b)})}
function render(){renderColors();$$('.cat').forEach(b=>b.classList.toggle('active',b.dataset.cat===current));const all=products[current]||[],list=color==='toutes'?all:all.filter(p=>p.family===color),pages=Math.max(1,Math.ceil(list.length/10));page=Math.min(page,pages);$('#sectionTitle').textContent=color==='toutes'?labels[current]:labels[current]+' — '+fam(color).label;$('#grid').innerHTML='';list.slice((page-1)*10,page*10).forEach(p=>{const card=document.createElement('article');card.className='card';card.dataset.id=p.id;card.innerHTML='<div class="photo"><img src="'+(p.imgs?.[0]||'scarf-1.jpg')+'" alt=""></div><div class="meta"><div class="name">'+p.name+'</div><div class="info">'+(p.info||'')+'</div><div class="shade">'+(p.shade||fam(p.family).label)+'</div><div class="buy"><div class="price">'+p.price+'</div><input class="qty" type="number" min="1" max="99" value="1"><button class="mini">🛒</button></div><div class="admin-tools '+(isAdmin?'':'hidden')+'"><button class="edit">Modifier</button><button class="delete">Supprimer</button></div></div>';card.querySelector('.photo').onclick=()=>openViewer(p);card.querySelector('.mini').onclick=()=>addCart(p,Math.max(1,parseInt(card.querySelector('.qty').value)||1));card.querySelector('.edit')?.addEventListener('click',()=>openProduct(p));card.querySelector('.delete')?.addEventListener('click',async()=>{if(confirm('Supprimer cet article ?')){await api('/api/admin/product/delete',{method:'POST',body:JSON.stringify({id:p.id})});await refreshCatalog()}});$('#grid').appendChild(card)});$('#pageLabel').textContent='Page '+page+' / '+pages;$('#prev').disabled=page<=1;$('#next').disabled=page>=pages;$('#addBtn').classList.toggle('hidden',!isAdmin);$('#adminBtn').textContent=isAdmin?'⚙️':'🔒';updateBadge()}
function addCart(p,q){const x=cart.find(x=>x.id===p.id);if(x)x.qty+=q;else cart.push({id:p.id,qty:q});ss(CART,JSON.stringify(cart));updateBadge();toast('Ajouté au panier')}
function itemById(id){for(const list of Object.values(products)){const p=list.find(x=>x.id===id);if(p)return p}}
function cartItems(){return cart.map(x=>({qty:x.qty,p:itemById(x.id)})).filter(x=>x.p)}
function updateBadge(){$('#cartBadge').textContent=cart.reduce((s,x)=>s+x.qty,0)}
function totals(){const sub=cartItems().reduce((s,x)=>s+euro(x.p.price)*x.qty,0),ship=delivery==='ship'&&sub?10:0;return{sub,ship,total:sub+ship}}
function renderCart(){const box=$('#cartList');box.innerHTML='';const items=cartItems();if(!items.length)box.innerHTML='<p style="text-align:center;color:#777">Panier vide</p>';items.forEach(x=>{const r=document.createElement('div');r.className='cart-row';r.innerHTML='<img src="'+(x.p.imgs?.[0]||'')+'"><div><b>'+x.p.name+'</b><small>'+(x.p.shade||'')+' · Quantité '+x.qty+' · '+x.p.price+'</small><input type="number" min="1" max="99" value="'+x.qty+'"></div><button class="remove">×</button>';r.querySelector('input').onchange=e=>{x.qty=Math.max(1,parseInt(e.target.value)||1);const c=cart.find(c=>c.id===x.p.id);c.qty=x.qty;ss(CART,JSON.stringify(cart));renderCart()};r.querySelector('.remove').onclick=()=>{cart=cart.filter(c=>c.id!==x.p.id);ss(CART,JSON.stringify(cart));renderCart();updateBadge()};box.appendChild(r)});const t=totals();$('#subtotal').textContent=money(t.sub);$('#shipping').textContent=money(t.ship);$('#total').textContent=money(t.total)}
function openViewer(p){viewer=p;viewerIndex=0;paintViewer();$('#viewer').classList.add('on')}
function paintViewer(){if(!viewer)return;$('#viewerImg').src=viewer.imgs?.[viewerIndex]||viewer.imgs?.[0]||'';$('#viewerCount').textContent=(viewerIndex+1)+' / '+Math.max(1,viewer.imgs?.length||1);$('#viewerName').textContent=viewer.name;$('#viewerInfo').textContent=(viewer.info||'')+' · '+(viewer.shade||'')}
function fillProductColors(family='vert',shade=''){const f=$('#productFamily'),s=$('#productShade');f.innerHTML=COLORS.filter(x=>x.id!=='toutes').map(x=>'<option value="'+x.id+'">'+x.label+'</option>').join('');f.value=family;const paint=()=>{const c=fam(f.value);s.innerHTML=(c.shades||[c.label]).map(v=>'<option>'+v+'</option>').join('');if(shade&&[...s.options].some(o=>o.value===shade))s.value=shade};f.onchange=()=>{shade='';paint()};paint()}
function openProduct(p=null){editing=p;$('#productTitle').textContent=p?'Modifier l’article':'Ajouter un article';$('#productName').value=p?.name||'';$('#productInfo').value=p?.info||'';$('#productPrice').value=p?.price||'';fillProductColors(p?.family||'vert',p?.shade||'');['photo1','photo2','photo3'].forEach(id=>$('#'+id).value='');show('productModal')}
const fileData=i=>new Promise(res=>{const f=i.files?.[0];if(!f)return res('');const r=new FileReader();r.onload=()=>res(String(r.result||''));r.onerror=()=>res('');r.readAsDataURL(f)});
async function adminDialog(){try{const st=await api('/api/status');$('#adminSetup').classList.toggle('hidden',st.adminsReady);$('#adminLogin').classList.toggle('hidden',!st.adminsReady||isAdmin);$('#adminHome').classList.toggle('hidden',!isAdmin);if(isAdmin)$('#adminName').textContent=adminName;show('adminModal')}catch{toast('Administration indisponible')}}
function trackingSaved(){try{return JSON.parse(sg(TRACK)||'null')}catch{return null}}
function updateTrackButton(){$('#trackingBtn').classList.toggle('hidden',!trackingSaved())}
function statusLabel(s){return s==='new'?'Commande reçue':s==='in_progress'?'En préparation':s==='done'?'Colis terminé':s==='sent'?'Envoyé':s}
async function openTracking(){const t=trackingSaved();if(!t)return;show('trackingScreen');$('#trackingContent').innerHTML='Chargement…';try{const d=await api('/api/order/status?id='+encodeURIComponent(t.id)+'&key='+encodeURIComponent(t.key));const order=d.order,steps=[['new','Commande reçue','Votre commande a bien été enregistrée'],['in_progress','En préparation','Votre commande est en préparation'],['done','Colis terminé','Votre colis est prêt à partir'],['sent','Envoyé','Votre colis a été envoyé']],idx=steps.findIndex(x=>x[0]===order.status);$('#trackingContent').innerHTML='<div class="track-title">'+order.orderNumber+'</div>'+steps.map((s,i)=>'<div class="track-step '+(i<idx?'done':i===idx?'current':'')+'"><i>'+(i<=idx?'✓':i+1)+'</i><div><b>'+s[1]+'</b><br><small>'+s[2]+'</small></div></div>').join('')}catch(e){$('#trackingContent').textContent=e.message}}
function orderItem(x){return '<div class="order-item">'+(x.image?'<img src="'+x.image+'">':'')+'<div><b>'+x.name+'</b><small>'+x.shade+' · Quantité '+x.qty+'</small></div></div>'}
async function loadOrders(){const box=$('#ordersList');box.innerHTML='Chargement…';try{const d=await api('/api/admin/orders');const list=(d.orders||[]).filter(o=>tab==='active'?['new','in_progress'].includes(o.status):tab==='ready'?o.status==='done':o.status==='sent');box.innerHTML=list.length?'':'<p style="text-align:center;color:#777">Aucune commande</p>';list.forEach(o=>{const c=document.createElement('div');c.className='order-card';let action=o.status==='new'?'<button class="order-action" data-act="claim">Je m’en occupe</button>':o.status==='in_progress'?(o.assignedTo===adminName?'<button class="order-action" data-act="finish">Commande terminée</button>':'<button class="order-action" disabled>'+o.assignedTo+' s’en occupe</button>'):o.status==='done'?'<button class="order-action" data-act="send">Envoyé</button>':'';c.innerHTML='<div class="order-head"><b>'+o.orderNumber+'</b><span class="status">'+statusLabel(o.status)+'</span></div><div class="customer">'+o.first+' '+o.last+' · '+o.phone+'<br>'+o.email+'<br>'+((o.address||o.postal||o.city)?o.address+' · '+o.postal+' '+o.city+'<br>':'')+o.deliveryText+(o.gift?.enabled?'<br>🎁 Cadeau'+(o.gift.forName?' pour '+o.gift.forName:'')+(o.gift.message?'<br>Message : '+o.gift.message:'')+(o.gift.hidePrice?'<br>Sans prix dans le colis':''):'')+'</div>'+(o.items||[]).map(orderItem).join('')+action;const b=c.querySelector('.order-action:not([disabled])');if(b)b.onclick=async()=>{try{await api('/api/admin/order/'+b.dataset.act,{method:'POST',body:JSON.stringify({id:o.id})});await loadOrders()}catch(e){toast(e.message)}};box.appendChild(c)})}catch(e){box.innerHTML='<p>'+e.message+'</p>'}}
$$('.cat').forEach(b=>b.onclick=()=>{current=b.dataset.cat;color='toutes';page=1;render()});$('#prev').onclick=()=>{page--;render();scrollTo(0,0)};$('#next').onclick=()=>{page++;render();scrollTo(0,0)};
$('#cartBtn').onclick=()=>{renderCart();show('cartScreen')};$('#trackingBtn').onclick=openTracking;$$('[data-back]').forEach(b=>b.onclick=()=>hide(b.dataset.back));$$('[data-close]').forEach(b=>b.onclick=()=>hide(b.dataset.close));
$('#viewerPrev').onclick=()=>{viewerIndex=(viewerIndex-1+(viewer.imgs?.length||1))%(viewer.imgs?.length||1);paintViewer()};$('#viewerNext').onclick=()=>{viewerIndex=(viewerIndex+1)%(viewer.imgs?.length||1);paintViewer()};
$('#shipBtn').onclick=()=>{delivery='ship';$('#shipBtn').classList.add('active');$('#pickupBtn').classList.remove('active');$('#pickupBox').classList.add('hidden');renderCart()};$('#pickupBtn').onclick=()=>{delivery='pickup';$('#pickupBtn').classList.add('active');$('#shipBtn').classList.remove('active');$('#pickupBox').classList.remove('hidden');renderCart()};
const markets=['Rennes — Marché des Lices','Rennes — Marché Sainte-Thérèse','Saint-Malo — Marché de Rocabey','Dinard — Marché central','Nantes — Marché de Talensac','La Baule — Marché central','Vannes — Marché des Lices','Lorient — Marché de Merville','Quimper — Marché des Halles','Brest — Marché Saint-Louis','Palaiseau — Marché'];
$('#marketSearch').oninput=e=>{const q=e.target.value.toLowerCase(),box=$('#marketResults');box.innerHTML='';if(q.length<2)return;markets.filter(m=>m.toLowerCase().includes(q)).slice(0,8).forEach(m=>{const b=document.createElement('button');b.textContent=m;b.onclick=()=>{market=m;$('#marketSelected').textContent='Choisi : '+m;box.innerHTML=''};box.appendChild(b)})};
$('#checkoutBtn').onclick=()=>{if(!cart.length)return toast('Panier vide');if(delivery==='pickup'&&!market)return toast('Choisis un marché');$('#orderPreview').innerHTML=cartItems().map(x=>'<div class="order-line"><img src="'+(x.p.imgs?.[0]||'')+'"><span><b>'+x.p.name+'</b><br>'+(x.p.shade||'')+' · Quantité '+x.qty+'</span><b>'+money(euro(x.p.price)*x.qty)+'</b></div>').join('');show('orderModal')};
$('#giftNo').onclick=()=>{gift=false;$('#giftNo').classList.add('active');$('#giftYes').classList.remove('active');$('#giftOptions').classList.add('hidden')};$('#giftYes').onclick=()=>{gift=true;$('#giftYes').classList.add('active');$('#giftNo').classList.remove('active');$('#giftOptions').classList.remove('hidden')};
$('#submitOrder').onclick=async()=>{const first=$('#first').value.trim(),last=$('#last').value.trim(),email=$('#email').value.trim(),phone=$('#phone').value.trim(),address=$('#address').value.trim(),postal=$('#postal').value.trim(),city=$('#city').value.trim();if(!first||!last||!email||!phone)return toast('Remplis nom, prénom, e-mail et téléphone');if(delivery==='ship'&&(!address||!postal||!city))return toast('Remplis l’adresse de livraison');const t=totals(),items=cartItems().map(x=>({name:x.p.name,shade:x.p.shade||'',qty:x.qty,price:x.p.price,lineTotal:money(euro(x.p.price)*x.qty),image:x.p.imgs?.[0]||''}));try{const d=await api('/api/order',{method:'POST',body:JSON.stringify({first,last,email,phone,address,postal,city,deliveryText:delivery==='pickup'?'À venir chercher — '+market:'Envoi à domicile',totalText:money(t.total),items,gift:{enabled:gift,forName:$('#giftFor').value.trim(),message:$('#giftMessage').value.trim(),hidePrice:$('#hidePrice').checked}})});ss(TRACK,JSON.stringify({id:d.id,key:d.key,orderNumber:d.orderNumber}));cart=[];ss(CART,'[]');updateBadge();updateTrackButton();hide('orderModal');hide('cartScreen');toast('Commande '+d.orderNumber+' enregistrée');setTimeout(openTracking,400)}catch(e){toast(e.message)}};
$('#adminBtn').onclick=adminDialog;$$('.admin-who').forEach(b=>b.onclick=()=>{selectedAdmin=b.dataset.admin;$$('.admin-who').forEach(x=>x.classList.toggle('active',x===b))});
$('#setupAdmin').onclick=async()=>{const j=$('#johnCode').value.trim(),m=$('#marleneCode').value.trim();if(j.length<4||m.length<4||j===m)return toast('Codes différents de 4 caractères minimum');try{const d=await api('/api/admin/setup',{method:'POST',body:JSON.stringify({johnCode:j,marleneCode:m})});token=d.token;adminName=d.admin;isAdmin=true;ss(TOKEN,token);ss(ADMIN,adminName);hide('adminModal');render()}catch(e){toast(e.message)}};
$('#loginAdmin').onclick=async()=>{try{const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify({admin:selectedAdmin,code:$('#adminCode').value})});token=d.token;adminName=d.admin;isAdmin=true;ss(TOKEN,token);ss(ADMIN,adminName);hide('adminModal');render()}catch(e){toast(e.message)}};
$('#logoutBtn').onclick=()=>{token='';adminName='';isAdmin=false;ss(TOKEN,'');ss(ADMIN,'');hide('adminModal');render()};$('#ordersBtn').onclick=()=>{hide('adminModal');show('ordersScreen');loadOrders()};$$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));loadOrders()});$('#changeCodeBtn').onclick=()=>{hide('adminModal');show('changeCodeModal')};
$('#saveCode').onclick=async()=>{const a=$('#oldCode').value,n=$('#newCode').value,c=$('#newCode2').value;if(n.length<4)return toast('4 caractères minimum');if(n!==c)return toast('Les nouveaux codes ne correspondent pas');try{await api('/api/admin/change-code',{method:'POST',body:JSON.stringify({currentCode:a,newCode:n})});hide('changeCodeModal');toast('Code changé')}catch(e){toast(e.message)}};
$('#addBtn').onclick=()=>openProduct();$('#saveProduct').onclick=async()=>{const name=$('#productName').value.trim(),info=$('#productInfo').value.trim(),price=$('#productPrice').value.trim(),family=$('#productFamily').value,shade=$('#productShade').value;if(!name||!price)return toast('Nom et prix obligatoires');const imgs=(await Promise.all([fileData($('#photo1')),fileData($('#photo2')),fileData($('#photo3'))])).filter(Boolean);try{await api('/api/admin/product/save',{method:'POST',body:JSON.stringify({id:editing?.id||null,category:current,name,info,price,family,shade,imgs})});hide('productModal');editing=null;await refreshCatalog(true);toast('Article enregistré')}catch(e){toast(e.message)}};
$('#collectionBtn').onclick=async()=>{loader(true);try{if('caches'in window){const ks=await caches.keys();await Promise.all(ks.filter(k=>k.startsWith('marlene-')).map(k=>caches.delete(k)))}if('serviceWorker'in navigator){const rs=await navigator.serviceWorker.getRegistrations();await Promise.all(rs.map(r=>r.update().catch(()=>{})))}await refreshCatalog(true);setTimeout(()=>location.replace(location.pathname+'?v='+Date.now()),500)}catch{loader(false);toast('Mise à jour impossible')}};
(async()=>{loader(true);await refreshCatalog(false);const all=Object.values(products).flat().map(p=>p.id);if(!sg(KNOWN))ss(KNOWN,JSON.stringify(all));updateBadge();updateTrackButton();loader(false);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=100').catch(()=>{})})();
})();